import requests
import base64
from db import database as db


def _session() -> tuple[str, requests.Session]:
    base = db.get_setting("confluence_url", "").rstrip("/")
    token = db.get_setting("confluence_token", "")
    s = requests.Session()
    s.headers.update({"Authorization": f"Bearer {token}", "Content-Type": "application/json"})
    return base, s


def create_page(title: str, body_html: str, parent_page_id: str = "") -> dict:
    base, s = _session()
    if not parent_page_id:
        parent_page_id = db.get_setting("confluence_parent_page_id", "")

    # Determine space key from parent page
    space_key = db.get_setting("confluence_space_key", "")
    if not space_key and parent_page_id:
        r = s.get(f"{base}/rest/api/content/{parent_page_id}", params={"expand": "space"}, timeout=10)
        if r.ok:
            space_key = r.json().get("space", {}).get("key", "")

    payload: dict = {
        "type": "page",
        "title": title,
        "space": {"key": space_key},
        "body": {"storage": {"value": body_html, "representation": "storage"}},
    }
    if parent_page_id:
        payload["ancestors"] = [{"id": parent_page_id}]

    r = s.post(f"{base}/rest/api/content", json=payload, timeout=15)
    r.raise_for_status()
    result = r.json()
    return {"id": result["id"], "url": f"{base}/pages/viewpage.action?pageId={result['id']}"}


def attach_file(page_id: str, filename: str, data: bytes, mime_type: str = "application/octet-stream"):
    base, s = _session()
    # Confluence REST requires multipart for attachments; override content-type header
    s.headers.pop("Content-Type", None)
    r = s.post(
        f"{base}/rest/api/content/{page_id}/child/attachment",
        headers={"X-Atlassian-Token": "no-check"},
        files={"file": (filename, data, mime_type)},
        timeout=30,
    )
    r.raise_for_status()


def build_drawio_page_html(title: str, drawio_xml: str) -> str:
    encoded = base64.b64encode(drawio_xml.encode()).decode()
    return f"""
<h1>{title}</h1>
<p>Architecture diagram generated by DevFlow.</p>
<ac:structured-macro ac:name="drawio">
  <ac:parameter ac:name="diagramName">{title}</ac:parameter>
</ac:structured-macro>
<p>Source (base64 draw.io XML):</p>
<ac:structured-macro ac:name="code">
  <ac:plain-text-body><![CDATA[{drawio_xml[:500]}...]]></ac:plain-text-body>
</ac:structured-macro>
"""
